# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Joonwon Kang
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
# baseurl: "/bay" # the subpath of the site
url: "https://jwkang24.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Experiences
    - name: Projects
    - name: Publications

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: jwkang@stanford.edu
  follow:
    - type: linkedin
      name: LinkedIn
      link: https://www.linkedin.com/in/joonwon-kang/
    - type: github
      name: GitHub
      link: http://github.com/JWKang24

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
